GET http://localhost:5138/games
###
GET http://localhost:5138/games/2
###
POST http://localhost:5138/games
Content-Type: application/json

{
    "name": "Killzone",
    "genreId": 1,
    "price": 49.99,
    "releaseDate": "2013-06-06"
}
###
PUT http://localhost:5138/games/2
Content-Type: application/json

{
    "name": "Fortnite",
    "genre": "Shooter",
    "price": 0,
    "releaseYear": "2013-06-06"
}
###
DELETE http://localhost:5138/games/2